#!/bin/sh
set -e

psql -tc "SELECT 1 FROM pg_database WHERE datname = '${MART_DB_NAME}'" | grep -q 1 || psql -c "CREATE DATABASE ${MART_DB_NAME}"
psql -c "REVOKE ALL ON DATABASE ${MART_DB_NAME} FROM PUBLIC;"
psql -c "CREATE USER ${MART_DB_USERNAME} WITH ENCRYPTED PASSWORD '${MART_DB_PASSWORD}';"
psql -c "GRANT ALL ON DATABASE ${MART_DB_NAME} TO ${MART_DB_PASSWORD};"

psql -c "CREATE ROLE readaccess;"
psql -c "GRANT USAGE ON SCHEMA public TO readaccess;"
psql -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO readaccess;"

psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readaccess;"

psql -c "CREATE USER ${MART_OPENMRS_DB_USERNAME} WITH ENCRYPTED PASSWORD '${MART_OPENMRS_DB_PASSWORD}';"
psql -c "GRANT readaccess ON DATABSE ${OPENMRS_DB_NAME} TO ${MART_OPENMRS_DB_USERNAME};"
