#!/bin/sh
set -e
psql -c "CREATE DATABASE ${METABADE_DB_NAME};"
psql -c "REVOKE ALL ON DATABASE ${METABADE_DB_NAME} FROM PUBLIC;"
psql -c "CREATE USER ${METABASE_DB_USERNAME} WITH ENCRYPTED PASSWORD '${METABASE_DB_PASSWORD}';"
psql -c "GRANT ALL ON DATABASE ${METABADE_DB_NAME} TO ${METABASE_DB_USERNAME};"

psql -c "CREATE ROLE readaccess;"
psql -c "GRANT USAGE ON SCHEMA public TO readaccess;"
psql -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO readaccess;"

psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readaccess;"

psql -c "CREATE USER ${METABASE_OPENMRS_DB_USERNAME} WITH ENCRYPTED PASSWORD '${METABASE_OPENMRS_DB_PASSWORD}';"
psql -c "GRANT readaccess ON DATABSE ${OPENMRS_DB_NAME} TO ${METABASE_OPENMRS_DB_USERNAME};"
psql -c "CREATE USER ${METABASE_MART_DB_USERNAME} WITH ENCRYPTED PASSWORD '${METABASE_MART_DB_PASSWORD}';"
psql -c "GRANT readaccess ON DATABSE ${MART_DB_NAME} TO ${METABASE_MART_DB_USERNAME};"
