{
    "name": "Lesotho Manufacturing",
    "summary": "Lesotho Manufacturing",
    "version": "16.0.1.0.0",
    "category": "Localization",
    "author": "MOH Lesotho",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "base",
        "contacts",
        "sale",
        "account",
        "stock",
        "mrp",
    ],
    "data": [
        "views/menu_overrides.xml",
        "views/view_form_overrides.xml",
        "views/action_overrides.xml",
        "views/view_table_overrides.xml",
    ],
    "installable": True,
    "application": False,
}
