{
    "name": "Lesotho Sale",
    "summary": "Lesotho Sale Customizations",
    "version": "16.0.1.0.0",
    "category": "Localization",
    "author": "eLMIS Development Team",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "base",
        "sale",
        "bahmni_sale",
        "lesotho_base",
        "stock",
        "mrp",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/menu_overrides.xml",
        "views/action_overrides.xml",
        "wizard/dispensing_pack_selection_wizard.xml",
        "views/view_order_overrides.xml",
        # "views/view_overrides.xml",
        # "data/migration_script.py",
        "views/view_overrides.xml",
    ],
    "installable": True,
    "application": False,
}
