version: '3.7'

x-default-logging: &default
  {}

x-loki-logging: &loki
  driver: loki
  options:
    loki-url: http://localhost:3100/loki/api/v1/push
    mode: non-blocking
    max-buffer-size: 4m
    loki-retries: "3"

x-log-config: &log-config
  # update this value to *loki if needed to see logs in grafana dashboard.
  <<: *loki

services:

  proxy:
    image: 'bahmni/proxy:${PROXY_IMAGE_TAG:?}'
    #volumes:
      # - ${CERTIFICATE_PATH}:/etc/tls
    ports:
      - '80:80'
      - '443:443'
    environment:
      TZ: ${TIMEZONE}
    logging: *log-config


  bahmni-config:
    image: '${CONFIG_IMAGE_NAME:?}:${CONFIG_IMAGE_TAG:?}'
    volumes:
      - '${CONFIG_VOLUME:?}:/usr/local/bahmni_config'
    environment:
      TZ: ${TIMEZONE}
    logging: *log-config

  bahmni-lab:
    profiles: ["lab-lite","emr","bahmni-lite"]
    image: 'bahmni/bahmni-lab:${BAHMNI_LAB_IMAGE_TAG:?}'
    environment:
      TZ: ${TIMEZONE}
    logging: *log-config

  openmrs:
    profiles: ["emr","bahmni-lite", "bahmni-mart"]
    image: bahmni/openmrs:${OPENMRS_IMAGE_TAG:?}
    environment:
      OMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OMRS_DB_HOSTNAME: ${OPENMRS_DB_HOST:?}
      OMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME:?}
      OMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      OMRS_CREATE_TABLES: ${OPENMRS_DB_CREATE_TABLES}
      OMRS_AUTO_UPDATE_DATABASE: ${OPENMRS_DB_AUTO_UPDATE}
      OMRS_MODULE_WEB_ADMIN: ${OPENMRS_MODULE_WEB_ADMIN}
      # OMRS_DEV_DEBUG_PORT: ${OMRS_DEV_DEBUG_PORT}
      OMRS_JAVA_SERVER_OPTS: ${OMRS_JAVA_SERVER_OPTS}
      OMRS_JAVA_MEMORY_OPTS: ${OMRS_JAVA_MEMORY_OPTS}
      SEND_MAIL: ${SEND_MAIL}
      MAIL_TRANSPORT_PROTOCOL: ${MAIL_TRANSPORT_PROTOCOL}
      MAIL_SMTP_HOST: ${MAIL_SMTP_HOST}
      MAIL_SMTP_PORT: ${MAIL_SMTP_PORT}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      MAIL_SMTP_STARTTLS_ENABLE: ${MAIL_SMTP_STARTTLS_ENABLE}
      MAIL_SMTP_SSL_ENABLE: ${MAIL_SMTP_SSL_ENABLE}
      MAIL_DEBUG: ${MAIL_DEBUG}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      OMRS_DOCKER_ENV: ${OPENMRS_DOCKER_ENV}
      TZ: ${TIMEZONE}
    #ports:
      # - ${OMRS_DEV_DEBUG_PORT}:${OMRS_DEV_DEBUG_PORT}
    volumes:
      - "${CONFIG_VOLUME:?}:/etc/bahmni_config/:ro"
      - "bahmni-lab-results:/home/bahmni/uploaded_results"
      # - "${BAHMNI_OPENMRS_MODULES_PATH:?}/:/openmrs/data/modules/"
      - 'bahmni-patient-images:/home/bahmni/patient_images'
      - 'bahmni-document-images:/home/bahmni/document_images'
      - 'bahmni-clinical-forms:/home/bahmni/clinical_forms'
      - 'configuration_checksums:/openmrs/data/configuration_checksums'

    depends_on:
      - openmrsdb
    logging: *log-config

  openmrsdb:
    image: ${OPENMRS_DB_IMAGE_NAME:?}
    restart: always
    profiles: ["emr","bahmni-lite", "metabase", "bahmni-mart"]
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${OPENMRS_DB_NAME:?}
      MYSQL_USER: ${OPENMRS_DB_USERNAME:?}
      MYSQL_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      TZ: ${TIMEZONE}
    volumes:
      - 'openmrsdbdata:/var/lib/mysql'
      - 'configuration_checksums:/configuration_checksums'
    
    logging: *log-config

  metabasedb:
    image: postgres:${METABASE_POSTGRES_IMAGE_TAG:?}
    restart: on-failure:[3]
    profiles: ["metabase", "bahmni-mart"]
    environment:
      POSTGRES_DB: ${METABASE_DB_NAME:?}
      POSTGRES_USER: ${METABASE_DB_USER:?}
      POSTGRES_PASSWORD: ${METABASE_DB_PASSWORD:?}
      TZ: ${TIMEZONE}
    volumes:
      - 'metabase-data:/var/lib/postgresql/data'


  metabase:
    image: bahmni/bahmni-metabase:${METABASE_IMAGE_TAG:?}
    restart: on-failure:[3]
    profiles: ["metabase", "bahmni-mart"]
    environment:
      MB_ADMIN_EMAIL: ${METABASE_ADMIN_EMAIL:?}
      MB_ADMIN_FIRST_NAME: ${METABASE_ADMIN_FIRST_NAME:?}
      MB_ADMIN_PASSWORD: ${METABASE_ADMIN_PASSWORD:?}
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_DB_NAME:?}
      MB_DB_PORT:  ${METABASE_DB_PORT:?}
      MB_DB_USER: ${METABASE_DB_USER:?}
      MB_DB_PASS: ${METABASE_DB_PASSWORD:?}
      MB_DB_HOST: ${METABASE_DB_HOST:?}
      OPENMRS_DB_HOST: ${OPENMRS_DB_HOST:?}
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OPENMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME:?}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      MART_DB_HOST: ${MART_DB_HOST:?}
      MART_DB_NAME: ${MART_DB_NAME:?}
      MART_DB_USERNAME: ${MART_DB_USERNAME:?}
      MART_DB_PASSWORD: ${MART_DB_PASSWORD:?}
      TZ: ${TIMEZONE}
    depends_on:
     - metabasedb

  martdb:
    image: postgres:${BAHMNI_MART_DB_IMAGE_TAG:?}
    profiles: ["bahmni-mart"]
    environment:
      POSTGRES_DB: ${MART_DB_NAME:?}
      POSTGRES_USER: ${MART_DB_USERNAME:?}
      POSTGRES_PASSWORD: ${MART_DB_PASSWORD:?}
      TZ: ${TIMEZONE}
    volumes:
      - 'mart-data:/var/lib/postgresql/data'


  mart:
    image: bahmni/bahmni-mart:${BAHMNI_MART_IMAGE_TAG:?}
    profiles: ["bahmni-mart"]
    environment:
      CRON_TIME: ${MART_CRON_TIME:?}
      MART_DB_HOST: ${MART_DB_HOST:?}
      MART_DB_NAME: ${MART_DB_NAME:?}
      MART_DB_USERNAME: ${MART_DB_USERNAME:?}
      MART_DB_PASSWORD: ${MART_DB_PASSWORD:?}
      OPENMRS_DB_HOST: ${OPENMRS_DB_HOST:?}
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OPENMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME:?}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      TZ: ${TIMEZONE}
    depends_on:
     - martdb
     - openmrsdb
     - openmrs
    volumes:
     - 'bahmni-clinical-forms:/home/bahmni/clinical_forms'

  bahmni-web:
    image: bahmni/bahmni-web:${BAHMNI_WEB_IMAGE_TAG:?}
    profiles: ["emr","bahmni-lite","bahmni-mart"]
    volumes:
      - "${CONFIG_VOLUME:?}:/usr/local/apache2/htdocs/bahmni_config/:ro"
    #   - "${BAHMNI_APPS_PATH:?}/ui/app/:/usr/local/apache2/htdocs/bahmni"
    #   - "${BAHMNI_APPS_PATH:?}/ui/node_modules/@bower_components/:/usr/local/apache2/htdocs/bahmni/components"
    environment:
      TZ: ${TIMEZONE}
    logging: *log-config

  implementer-interface:
    image: bahmni/implementer-interface:${IMPLEMENTER_INTERFACE_IMAGE_TAG:?}
    profiles: ["implementer-interface","emr","bahmni-lite"]
    #volumes:
    #  - "${IMPLEMENTER_INTERFACE_CODE_PATH:?}/dist:/usr/local/apache2/htdocs/implementer-interface"
    depends_on:
      - openmrs
    environment:
      TZ: ${TIMEZONE}
    logging: *log-config

  reports:
    image: bahmni/reports:${REPORTS_IMAGE_TAG:?}
    profiles: ["reports","bahmni-lite"]
    environment:
      OPENMRS_DB_HOST: ${OPENMRS_DB_HOST:?}
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OPENMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME:?}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      OPENMRS_HOST: ${OPENMRS_HOST:?}
      OPENMRS_PORT: ${OPENMRS_PORT:?}
      REPORTS_DB_SERVER: reportsdb
      REPORTS_DB_NAME: ${REPORTS_DB_NAME:?}
      REPORTS_DB_USERNAME: ${REPORTS_DB_USERNAME:?}
      REPORTS_DB_PASSWORD: ${REPORTS_DB_PASSWORD:?}
      TZ: ${TIMEZONE}
    volumes:
      - "${CONFIG_VOLUME:?}:/etc/bahmni_config/:ro"
    depends_on:
      - reportsdb
      - openmrsdb
      - bahmni-web
    logging: *log-config

  reportsdb:
    platform: linux/amd64
    image: mysql:5.7
    profiles: ["reports","bahmni-lite"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${REPORTS_DB_NAME:?}
      MYSQL_USER: ${REPORTS_DB_USERNAME:?}
      MYSQL_PASSWORD: ${REPORTS_DB_PASSWORD:?}
      TZ: ${TIMEZONE}
    logging: *log-config

  patient-documents:
    image: 'bahmni/patient-documents:${PATIENT_DOCUMENTS_TAG:?}'
    profiles: ["emr","bahmni-lite"]
    volumes:
      - 'bahmni-document-images:/usr/share/nginx/html/document_images'
      - 'bahmni-lab-results:/usr/share/nginx/html/uploaded_results'
    environment:
      OPENMRS_HOST: ${OPENMRS_HOST:?}
      TZ: ${TIMEZONE}
    depends_on:
      - openmrs
    logging: *log-config

  appointments:
    image: bahmni/appointments:${APPOINTMENTS_IMAGE_TAG:?}
    profiles: ["emr","bahmni-lite"]
    environment:
      TZ: ${TIMEZONE}
    # volumes:
    # - "${APPOINTMENTS_PATH:?}/dist/:/usr/local/apache2/htdocs/appointments"

  atomfeed-console:
    image: bahmni/atomfeed-console:latest
    profiles: ["atomfeed-console"]
    environment:
      OPENMRS_DB_HOST: ${OPENMRS_DB_HOST}
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME}
      OPENMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD}
      TZ: ${TIMEZONE}

volumes:
  openmrs-data:
  openmrsdbdata:
  bahmni-patient-images:
  bahmni-document-images:
  bahmni-clinical-forms:
  bahmni-config:
  configuration_checksums:
  mart-data:
  metabase-data:
  bahmni-lab-results:
