name: Deploy to Cure QA Env
on:
  push:
    branches:
      - cure-master
    paths:
      - 'bahmni/**'
      - '.github/workflows/cure_qa_deploy.yaml'
  # repository_dispatch:
  #   types:
  #     - bahmni-helm-publish-event
  #     - openmrs-db-publish-event
  #     - bahmni-proxy-publish-event
  workflow_dispatch:
    # inputs:
    #   update_bahmni_option:
    #     description: 'Choose the option to update Bahmni. "Update without removing volumes" or "Update and remove volumes"'
    #     required: true
    #     type: choice
    #     default: update_without_removing_volumes
    #     options:
    #       - update_without_removing_volumes
    #       - update_and_remove_volumes
# env:
#   UPDATE_BAHMNI_OPTION: ${{ github.event.inputs.update_bahmni_option || 'update_without_removing_volumes'}}

jobs:
  deploy:
    name: Deploy to QA Instance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: Authenticate the Service Account
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.CURE_EMR_DEPLOYMENTS_SERVICE_ACCOUNT_KEY }}
      - id: 'compute-ssh'
        name: Send commands via SSH
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: '${{ secrets.CURE_EMR_QA_INSTANCE_NAME }}'
          zone: 'us-central1-a'
          user: '${{ secrets.CURE_EMR_DEPLOYMENTS_USERNAME }}'
          ssh_private_key: '${{ secrets.CURE_EMR_DEPLOYMENTS_SSH_PRIVATE_KEY }}'
          command: |
            echo "hello GCP!"
      - id: 'test'
        name: Print the command outputs
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'