name: GCP GithubActions
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test-conenctivity:
    name: Test GHA <-> GCP Connectivity
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v3
    
    - id: 'auth'
      name: Authenticate the Service Account
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.CURE_EMR_DEPLOYMENTS_SERVICE_ACCOUNT_KEY }}

    - id: 'compute-ssh'
      name: Send commands via SSH
      uses: 'google-github-actions/ssh-compute@v0'
      with:
        instance_name: '${{ secrets.CURE_EMR_QA_INSTANCE_NAME }}'
        zone: 'us-central1-a'
        user: '${{ secrets.CURE_EMR_DEPLOYMENTS_USERNAME }}'
        ssh_private_key: '${{ secrets.CURE_EMR_DEPLOYMENTS_SSH_PRIVATE_KEY }}'
        command: |
          echo "hello GCP"
          pwd
          whoami
          ls -al

    # Example of using the output
    - id: 'test'
      name: Print the command outputs
      run: |-
        echo '${{ steps.compute-ssh.outputs.stdout }}'
        echo '${{ steps.compute-ssh.outputs.stderr }}'
